title: Yangyi Chen 
logo: /assets/imgs/photo2.jpeg
description: CS Ph.D. Candidate @ UIUC   |     YangyiChen6666 [AT] gmail.com
# show_downloads: true
google_analytics:
theme: jekyll-theme-time-machine
