title: Yangyi Chen 
logo: /assets/imgs/self-photo.jpeg
description: CS PhD Student @ UIUC   |     YangyiChen6666 [AT] gmail.com
# show_downloads: true
google_analytics:
theme: jekyll-theme-time-machine
